### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MohanadSinan** [MohanadSinan/goldenwaste-sda-hackathon#1]
##### Task 1

- [x] Remove the unnecessary files from [EC2_VPC](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/tree/EC2_VPC) branch.
  - [x] Remove [Jenkinsfile-EBS3](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/blob/EC2_VPC/Jenkinsfile-EBS3) (and replace it with a new Jenkinsfile).
  - [x] Remove [azure-pipelines.yml](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/blob/EC2_VPC/azure-pipelines.yml) (not needed because the project will run in AWS).
  - [x] Remove [mvnw.cmd](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/blob/EC2_VPC/mvnw.cmd) (not needed because the project will run in Linux).

##### Task 2

- [ ] Update README.md file.
  - [ ] Write the introduction of the project.
  - [ ] Write the requirements of this project.
  - [ ] Write the method to deploy this project in EC2 instance using custom VPC.
  - [ ] Write the results and the conclusion.
  - [x] Write the name of the contributors team.

##### Task 3

- [x] Recreate the Jenkinsfile.
  - [x] Add the credentials of AWS account
  - [x] Add the artifact name (see [buildspec.yml](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/blob/EC2_VPC/buildspec.yml) for more information)
  - [x] Add the S3 bucket name.
  - [x] Add the SonarQube variables.
  - [x] Add the following stages (see [buildspec.yml](https://github.com/MohanadSinan/goldenwaste-sda-hackathon/blob/EC2_VPC/buildspec.yml) for more information):

    <html>
    1. 'Validate' stage<br>
    2. 'Build' stage<br>
    3. 'Test' stage<br>
    4. 'Quality Scan' stage<br>
    5. 'Package' stage<br>
    6. 'Publish artefacts to S3 Bucket' stage
        </html>

##### Task 4

- [x] Create and add CloudFormation file with these resources:

    - **VPC** (GoldenWaste-vpc) *(CIDR = 10.0.0.0/16)*
      - **2 Subnets:**
        - Public Subnet (GoldenWaste-subnet-public1-us-east-1a) *(CIDR = 10.0.0.0/20)*
        - Private Subnet  (GoldenWaste-subnet-private1-us-east-1a) *(CIDR = 10.0.128.0/20)*
      - **2 Route tables:**
        - Public Route Table (GoldenWaste-rtb-public) *(0.0.0.0/0 routes to Internet Gateway)*
        - Private Route Table (GoldenWaste-rtb-private1-us-east-1a) *(0.0.0.0/0 routes to Public NAT Gateway and Prefix list through Gateway Endpoint to S3)*
      - **3 Network connections:**
        - Internet Gateway (GoldenWaste-igw) (Internet routes to 1 public subnet and 1 private subnet routes to the Internet)
        - Public NAT gateway (GoldenWaste-nat-public1-us-east-1a) *(1 ENI with 1 EIP)*
        - Gateway endpoint to S3 (GoldenWaste-vpce-s3)
    - **3 EC2 Instances** (Ubuntu Image)
      - Ansible Master (in private subnet?) *(install Ansible)*
      - Database (in private subnet)
      - Web App (in public subnet)

##### Task 5

- [x] Create and add Ansible inventory file.
- [x] Create and add the following Ansible playbooks:
  - [x] install Java Maven and clone the repo from github on the web application instance.
  - [x] install Jenkins and SonarQube on the master instance.
  - [x] install and configure MySQL on the database instance.
  - [x] Create and add shell scripts to run SonarQube.
  - [x] something else
